### ISSUE TITLE
Naming: docs/modules/ROOT —> docs/modules/admin ?

### ISSUE THREAD

**Issue by mmattel** [owncloud/docs#102]
Could that naming be changed so the foldername represents the topic ?

**Comment by settermjd** [comment]
From reading through https://docs.antora.org/antora/1.1/component-structure/, perhaps I mis-read it the first time, or it's been updated since I last read through it. However, as I understand it now, there doesn't need to be a ROOT folder. It could be renamed to `admin_manual`, and the documentation would still build correctly. Come to think of it, by doing so, both the generated URL structure and the file/directory structure would be better as a result of renaming it.

**Comment by settermjd** [comment]
However, we'd need to create a ROOT module that acted as a placeholder for the documentation.

**Comment by settermjd** [comment]
Decided to experiment with changing this, as a result of [your feedback](https://github.com/owncloud/docs/pull/137#discussion_r223120413) in #137.

**Comment by mmattel** [comment]
Closing, merged
