### ISSUE TITLE
Appliance ClamAV wrong document link

### ISSUE THREAD

**Issue by voroyam** [owncloud/docs#1461]
This is old and wrong:
https://github.com/owncloud/docs/edit/master/modules/admin_manual/pages/appliance/Clamav.adoc

This was changed to have lower case file name -> clamav.adoc and moved to /appliance/configuration/ folder. In the nav.adoc it's written correctly: 

**** xref:appliance/configuration/clamav.adoc[ClamAV]

which is also the name of the document:
https://github.com/owncloud/docs/blob/master/modules/admin_manual/pages/appliance/configuration/clamav.adoc

But in the web page it's still rendered with a big `C`
 
https://doc.owncloud.com/server/admin_manual/appliance/Clamav.html
doc.owncloud.com

I don't know where to check other than GitHub and the nav.adoc page.

**Comment by settermjd** [comment]
@voroyam, docs are no longer deployed from master, only from the 10.2, 10.1, and 10.0 branches. Given that, I think that the old master deployment wasn't cleaned up. I'll do some further investigation and report here what I find.

**Comment by settermjd** [comment]
@tboerger said "_so far the deployment is not deleting files, otherwise the pdf documents would also be dropped which are deployed by different branches because of lacking antora support for it...you should anyway define aliases for files which had been renamed._" Given that, I'll create an alias for this file to resolve the problem. Thanks for continuing to chase this issue, @voroyam.

**Comment by voroyam** [comment]
Alright. Thanks @settermjd and @tboerger
