### ISSUE TITLE
TOC in PDF manuals broken

### ISSUE THREAD

**Issue by ellipticview** [owncloud/docs#1568]
The Table of Content (TOC) in the PDF manuals are broken. In particular in the navigation pane of the PDF viewer.

- There is text that doesn't belong in the TOC
- All entries are under the introduction
- The granularity of the entries is questionable (i.e. hundreds of pages between two TOC lines). That does not make it feasible to use the TOC to navigate a document

E.g. in https://doc.owncloud.com/server/10.2/admin_manual/ownCloud_Admin_Manual.pdf

![image](https://user-images.githubusercontent.com/8074771/61995829-a2388080-b08d-11e9-9bae-c455e1036917.png)

**Comment by settermjd** [comment]
@ellipticview, thanks for reporting this. For the most part, the items in the TOC are the same as that within the HTML version of the docs. However, I agree that the location of the TOC needs to be improved.

**Comment by tboerger** [comment]
@settermjd it's not the same as on HTML as you are generating it on your own with the sed magic within the shell script. Looks like a wrong file gets included in the order, `ownCloud supports eight user roles. These are:` should simply not be the main headline for the TOC.

**Comment by settermjd** [comment]
After some investigation, the table of contents title is set as it is in the PDF copy of the admin manual because [the toc-title attribute](https://asciidoctor.org/docs/user-manual/#user-toc-title) was used in `modules/admin_manual/pages/configuration/user/user_roles.adoc`. 

When generating the HTML version of the documentation, this is fine, because each page is compiled in a stand-alone context. The net result is that the attribute will only affect the page that it's set on. 

However, when generating the PDF copy of the admin manual, all of the content is combined into, effectively, one page. Much like a PHP array, attributes can be specified multiple times, with the latter values overwriting the former ones. Consequently, the document's table of contents was overwritten by the value on one specific page.
