### ISSUE TITLE
Inter-link or consolidate logging pages

### ISSUE THREAD

**Issue by michaelstingl** [owncloud/docs#1638]
I found logging-related content on different places. All are isolated, but it would be more useful to have them at one place, or at least linked:

- [`ownCloud Server / Admin Manual / Configuration / Server / Logging Configuration`](https://doc.owncloud.com/server/10.2/admin_manual/configuration/server/logging_configuration.html)
- [`ownCloud Server / Admin Manual / Configuration / Server / Request Tracing`](https://doc.owncloud.com/server/10.2/admin_manual/configuration/server/request_tracing.html)
- [`ownCloud Server / Admin Manual / Troubleshooting / Retrieve Log Files and Configuration Settings`](https://doc.owncloud.com/server/10.2/admin_manual/troubleshooting/providing_logs_and_config_files.html)

## What Type Of Content Change Is This? (Optional)
- [ ] New Content Addition
- [ ] Old Content Deprecation
- [x] Existing Content Simplification
- [ ] Bug Fix to Existing Content

## Which Manual Does This Relate To? (Optional)
- [x] Admin Manual
- [ ] Developer Manual
- [ ] User Manual
- [ ] Android
- [ ] iOS
- [ ] Branded Clients
- [ ] Desktop Client
- [ ] Other

**Comment by settermjd** [comment]
@michaelstingl, can you set a priority for this issue?

**Comment by settermjd** [comment]
@michaelstingl, I just had a look at the various files. You're spot on. I'll get this actioned today.

**Comment by voroyam** [comment]
@michaelstingl My document was not related exclusively to logging.

It was a support related document that had instructions to get the log files (yes) but also the config report (which is not a log file) and the ldap config (which is also not a log file). 

When customers look for "how do I get the freaking log files that the support guy asked me about" they don't look in logging configurations because they don't want to configure their logs right now.

My document was in the troubleshooting section of the admin page, the place to look when you are in trouble, contacted support, and want to get something for support.

In my view it's a gross generalization to put my document (without asking me) on some remote place where you can't find it when you don't know what you are looking for. 

Please revert the change and restore the troubleshooting section.
