### ISSUE TITLE
php upgrade instruction should not advertise php 5.6 or php 7.0 any more

### ISSUE THREAD

**Issue by jnweiger** [owncloud/docs#2168]
https://github.com/owncloud/docs/blob/10.3/modules/admin_manual/pages/maintenance/upgrading/upgrade_php.adoc
mentions php 5.6 and php 7.0 as the way to go. This is outdated.

**Comment by settermjd** [comment]
I agree that instructions for PHP 5.6 absolutely must be removed, as it's been EOL since 31 Dec 2018. However, 10.3 requires 7.0.8 as a minimum PHP version, and master lists 7.1 as the minimum required version. 

I suggest removing PHP 5.6 instructions, and adding options for 7.0, 7.1, 7.2, & 7.3. That said, 7.0 was EOL on 10 Jan 2019 and 7.1 was EOL on 1 Dec 2019. But, I'm trying to balance that with the variety of installations that customers and other users may have.

**Comment by phil-davis** [comment]
As of today, installations must be running PHP 7.0 to 7.3 before upgrading. So yes, we should remove mention of 5.6. I think that will work - e.g. core 8.2.11 supports PHP up to 7.2, so you can bump PHP all the way to 7.2 while running ownCloud core 8.2.11, then you can upgrade your ownCloud to 10.3.2

If you have ownCloud core before 8.2.11 then you are required to first upgrade to 8.2.11 anyway.

Along with release of core 10.4, we need to remove mention of PHP 7.0. That will not cause a problem - you will still be able to install PHP 7.1 or 7.2, then upgrade from ownCloud core 8.2.11 to 10.4

**Comment by settermjd** [comment]
Thanks for the further information, @phil-davis.
