### ISSUE TITLE
Document the setup of OfficeOnline

### ISSUE THREAD

**Issue by micbar** [owncloud/docs#2266]
Currently, only @DeepDiver1975 knows how to configure it.

## What Needs to be Documented?
Setup of an OfficeOnline Server

## Where Does This Need To Be Documented?
Admin Docs

## Why Should This Change Be Made? (Optional)
Not existing.

## What Type Of Content Change Is This? (Optional)
- [x] New Content Addition
- [ ] Old Content Deprecation
- [ ] Existing Content Simplification
- [ ] Bug Fix to Existing Content

## Which Manual Does This Relate To? (Optional)
- [x] Admin Manual
- [ ] Developer Manual
- [ ] User Manual
- [ ] Android
- [ ] iOS
- [ ] Branded Clients
- [ ] Desktop Client
- [ ] Other

**Comment by settermjd** [comment]
@DeepDiver1975, can you provide the core of what you know so that this issue can be documented, please?

**Comment by DeepDiver1975** [comment]
All config parameters are documented in the readme https://github.com/owncloud/wopi#setup

What was causing trouble in the past is the lack of understanding how https/ssl works :see_no_evil: 

owncloud as well as the office server need to be accessible via https with valid certs. Selfsigned certs are discouraged because one needs to insert them into windows server .... this is usually yet another step where people fail.
^ but this is not really wopi specific - this is common paractice

**Comment by voroyam** [comment]
@micbar I documented everything I know here https://github.com/owncloud/administration-internal/wiki/Office-Online

**Comment by settermjd** [comment]
> @micbar I documented everything I know here https://github.com/owncloud/administration-internal/wiki/Office-Online

I have very little experience administering Windows servers. Do you have time to talk abour your notes, @voroyam?

**Comment by voroyam** [comment]
@micbar are you sure we want our internal certificate generating script in the official docs?

I am confused.

Here is the current PR for the documentation of this issue: https://github.com/owncloud/docs/pull/2313

**Comment by DeepDiver1975** [comment]
Why shall we document how 3rd party software is to be setup? Especially since we are not microsoft experts.
There should be a hell of information out there on how to setup office online.
