### ISSUE TITLE
https://owncloud.org/changelog/server/ improvements

### ISSUE THREAD

**Issue by jnweiger** [owncloud/docs#2402]
I'd like to suggest the following changes to how we present the changelog

* Currently https://owncloud.org/changelog/server starts with a link to owncloud 9.  I find it a confusing start, when follwing a link from a 10.4.0 annoucement. It should go to the bottom. It follows logically right **after** the 10.0.0 changelog section.

* The UNRELEASED section should be collaped by default. If users want to know about the future, they can expose the section. This way the changelog would start with released changes, which is more relevant to the end users.

* All H1 headings have a version number with an <a href...>. A name="VERSION" should be added, so that e.g. https://owncloud.org/changelog/server/#10.4.0 would work. That is most helpful for mailings and release notes.

**Comment by pmaier1** [comment]
Yes, I absolutely agree with these improvements. Still, this is not part of the docs. Will put this into the right channels :)

**Comment by hurradieweltgehtunter** [comment]
Thanks @jnweiger for the improvements. I agree but there are certain limitations.
The Changelog page is automatically created  based on https://raw.githubusercontent.com/owncloud/core/master/CHANGELOG.md
Wordpress fetches the contents once an hour, parses the markdown code, converts it to HTML and saves it in the WP DB. Thus, only elements/markup existing in markdown are possible on this page. Collapsing elements etc. is not one of them.

> Currently https://owncloud.org/changelog/server starts with a link to owncloud 9. I find it a confusing start, when follwing a link from a 10.4.0 annoucement. It should go to the bottom. It follows logically right after the 10.0.0 changelog section.

This is not part of the changelog.md file, so it's changeable in Wordpress. We put it above because noone will find the link if it is a the bottom of the (looong) changelog page. If we still want to change that I can do this.

> All H1 headings have a version number with an . A name="VERSION" should be added, so that e.g. https://owncloud.org/changelog/server/#10.4.0 would work. That is most helpful for mailings and release notes.

As mentioned above this is parsed from the .md file. @micbar is the right person to talk to about that.

I know it's unfortunate to have those limitations but the HUGE benefit is that noone has to manually write and keep track of the changelog page. As long we can use the automatic parsing and don't run into bigger problems I'd always prefer this method.

**Comment by micbar** [comment]
> All H1 headings have a version number with an . A name="VERSION" should be added, so that e.g. https://owncloud.org/changelog/server/#10.4.0 would work. That is most helpful for mailings and release notes.

You mean the github links on the version? https://github.com/owncloud/core/compare/v10.3.2...v10.4.0 this is the github history betweed these two tags.

If you want an anchor link, we need to investigate how we can pass it from markdown to html

**Comment by jnweiger** [comment]
Yep automation is key -> forget the collapsing idea. 
V9 link underneath is preferable to me even though the page is long, imho.
Nname attributes to be added by the generator scripts. Ok.

**Comment by hurradieweltgehtunter** [comment]
V9 linkwas moved to the bottom

**Comment by voroyam** [comment]
@jnweiger now the latest release is on top. Better?

**Comment by voroyam** [comment]
![image](https://user-images.githubusercontent.com/24212810/110403500-778e1680-807d-11eb-8eb9-3ce05508d262.png)

**Comment by jnweiger** [comment]
Much better. Thanks!
