### ISSUE TITLE
LDAP quota priority confusing

### ISSUE THREAD

**Issue by voroyam** [owncloud/docs#2583]
### What?
I have read the LDAP docs and I find the LDAP priority description confusing. I don't get what LDAP Quota have to be set where in ownCloud.

### Where?
https://doc.owncloud.com/server/admin_manual/configuration/user/user_auth_ldap.html#special-attributes

### Why?
Because if I find it confusing then chances are that our customers will too and they will open support cases.

-----

![image](https://user-images.githubusercontent.com/24212810/79738690-61f4ee80-82fd-11ea-8ac8-3f5b0e72c653.png)

**Comment by voroyam** [comment]
@NannaBarz you can track this issue here or add more details

**Comment by NannaBarz** [comment]
### What?
I have some understanding problems with the 3rd and 4th point. 
After reading the documentation I only find two ways to set the quota
1. over the user management page (for each user)
2 over the quota field in the LDAP wizzard (for all users)

I'm missing the LDAP per/attribute setting so I don't exactly know where is the difference between the 3rd and 4th point.

**Comment by settermjd** [comment]
@cdamken, can you provide further input, please?

**Comment by NannaBarz** [comment]
Ok after creating a own attribute in the AD I think i got it. 
The for me missing part was, that you have to create the attribute in the AD.

**Comment by cdamken** [comment]
The behavior should be as described here: https://github.com/owncloud/enterprise/issues/1813#issuecomment-281051811

### The expected behavior:

1.- ownCloud default quota is set as 1 choice.
2.- Administrators can modify the quota in the user page.
3.- If the LDAP quota is set -> overrides ownCloud quotas.
4.- If quota per attribute in LDAP is set -> overrides LDAP quota.

Administrators are not allowed to modify quota over the user's page anymore, update works in LDAP only!

**Comment by voroyam** [comment]
I think we should replace the existing 1-4 bullet points with the ones from @cdamken They make more sense to me.

**Comment by voroyam** [comment]
https://github.com/owncloud/docs/pull/3293

**Comment by mschreml** [comment]
done

backports:

10.6 - #3298
10.5 - #3299
