### ISSUE TITLE
Searched content leads to 404

### ISSUE THREAD

**Issue by ChrisEdS** [owncloud/docs#2610]
We have an error in the documentation. Searched content will lead to a `404` due to misconfiguration in link creation. For example

### Steps to reproduce
1. Go to `doc.owncloud.com`
2. You get redirected to `doc.owncloud.com/server/10.4`
3. Search for `config.php`
4. Click on the second search result 
![image](https://user-images.githubusercontent.com/33026403/80106035-9d9bec80-8579-11ea-86f6-d74b7fa656ae.png)
5. Get a `404` page

### Actual behavior
In that case, we want to see `doc.owncloud.com/server/10.0/admin_manual/configuration/server/config_sample_php_parameters.html` but we get
`doc.owncloud.com/server/10.4/undefined/server/10.0/admin_manual/configuration/server/config_sample_php_parameters.html`

### Expected behavior
`server/10.4/undefined/` part should be not part of the URL.

### Related
https://github.com/owncloud/docs/commit/ab615dcb3df8ae969863249c08971fe7f51640af

**Comment by felixboehm** [comment]
search.owncloud.com (elasticsearch) returns the bogus links in the json response.
elastic is maybe indexing wrong stuff. Any changes in docs which let elastic find broken content?

**Comment by felixboehm** [comment]
index is generated in https://github.com/owncloud/docs/blob/master/generator/generate-site.js

**Comment by dschmidt** [comment]
I cannot reproduce, has something changed meanwhile?

The "Config.php Parameters" in 10.0 result does not show up for me in the search results, all other results have no undefined in their url.

**Comment by dschmidt** [comment]
> search.owncloud.com (elasticsearch) returns the bogus links in the json response.
> elastic is maybe indexing wrong stuff. Any changes in docs which let elastic find broken content?

Any way for me to reproduce?

**Comment by ChrisEdS** [comment]
> I cannot reproduce, has something changed meanwhile?

I cleared the cache and tried a different browser, the error is still reproducible. Try to search for `config.php`click on the first search result.

**Comment by dschmidt** [comment]
Okay, yes, I see a bunch of occurences in

```
curl 'https://search.owncloud.com/_search?q=config.php' \
  -X 'POST' \
  -H 'authority: search.owncloud.com' \
  -H 'content-length: 0' \
  -H 'pragma: no-cache' \
  -H 'cache-control: no-cache' \
  -H 'authorization: Basic ZG9jczpjQURMNkREQUtFQnJrRk1ydmZ4WEV0WW0=' \
  -H 'user-agent: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_4) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/81.0.4044.122 Safari/537.36' \
  -H 'dnt: 1' \
  -H 'accept: */*' \
  -H 'origin: https://doc.owncloud.com' \
  -H 'sec-fetch-site: same-site' \
  -H 'sec-fetch-mode: cors' \
  -H 'sec-fetch-dest: empty' \
  -H 'referer: https://doc.owncloud.com/' \
  -H 'accept-language: de,en-GB;q=0.9,en;q=0.8,en-US;q=0.7' \
  --compressed```

(Authorization is just a generic user/password for elasticsearch, it's not confidential)

**Comment by dschmidt** [comment]
AFAICT the issue is that `playbook.site.url`  is `undefined` [here](https://github.com/owncloud/docs/blob/master/generator/generate-site.js#L43).

`site.url` is set in `site.yml` in branches 10.4, 10.3, 10.2 but not in 10.0 or 10.1.

I'm wondering when which jobs overwrites (which part of) the index ... wondering if changes were only partly backported to old branches or something like that. Investigating further...

**Comment by dschmidt** [comment]
I cannot reproduce this by creating an index from the branches where site.url is set. 
To me it looks this repo is designed in a way that some things need to be kept consistent accross all branches:
The generator script is exactly the same in all branches and whichever branch is run in CI "wins" and overrides the index (unless I'm overlooking something) for all branches. So when something breaks in one branch (because a setting in one config file is missing), the index breaks occasionally when exactly that branch was the last to be run in CI...

Maybe it would be a saner approach to only update the index from master. The initial idea was probably to have the index updated whenever something gets pushed to any of the branches, but even then we could simply start a downstream drone job.
If my understanding of the setup is correct that would be a much saner approach IMHO. 

https://github.com/owncloud/docs/pull/2617
https://github.com/owncloud/docs/pull/2618

Correct me, if I understand anything wrong ...

**Comment by phil-davis** [comment]
Note: there was a policy implemented a while ago to no longer backport to all the branches. That mistakes/reorganisations/rewording... would no longer be backported to 10.0 10.1 or 10.2

Only 10.3 and 10.4 would be maintained.

A side-effect of that might be that structural and "code" changes have happened in master, 10.4 and 10.3 but that 10.2 10.1 and 10.0 do not have the "latest" structure and "code" - so they behave differently and perhaps have impact on searches...
