### ISSUE TITLE
Add the domain name of the appliance in the Collabora Online server field

### ISSUE THREAD

**Issue by Akidxx** [owncloud/docs#2849]
After installing and configuring Collabora online to owncloud using appliance:
The domain name of the appliance should be updated in the 'Collabora Online server' (
Settings > Admin > Additional > Collabora

(As access with HTTPS using a domain name is required then the domain name should also be updated  in the 'Collabora Online server' 

![Screenshot from 2020-11-03 10-25-07](https://user-images.githubusercontent.com/15052479/97968483-fa951c80-1dbe-11eb-8490-6ca8495dc16f.png)

**Comment by voroyam** [comment]
please add a screenshot and the relevant page to add this content to

**Comment by erwinpalma** [comment]
Hello @Akidxx

According to the Univention Appliance documentation.

"Due to the deep integration of services in UCS, changing the hostname or other basic settings (which potentially affect the whole domain) is no trivial task.
The hostname is used by DNS, LDAP, Kerberos, Samba4, SSL certificates, and many more services in various configs and directory services. All these occurrences have to be adjusted."

The easiest way is to assign the IP manually into the Collabora configuration section, instead of using the default DNS name provided by the Appliance.

You will find more information at the following links:

https://help.univention.com/t/changing-hostname-on-ucs/3010
https://docs.software-univention.de/installation-4.0.html#appliance:use:auto:profile
