### ISSUE TITLE
WND Configuration Quick Guide

### ISSUE THREAD

**Issue by enbrnz** [owncloud/docs#2872]
This new document should enable an administrator to install and configure a Windows Network Drive share user home drive. This uses user authentication and enables the use of the sync client using the WND listener and process queue.

1. Installation
samba packages & libraries
- enable ownCloud app windows_network_drive
	occ / WebUI

2. Configuration
2.1 WebUI
- external storage settings of ownCloud, create:
- share: server / path
- credentials: to authenticate use save in database, for using sync client
- user availability
- enable sharing
- "Check for changes"

2.2 Linux
- setup windows network drive listener
two options:
- systemd service
- cron with flock

- setup the process queue

2.3 Alternative to WebUI config of share, use `occ`

3. Troubleshooting
- process queue will not work if there is a backslash in the share path configured in webui

## What Type Of Content Change Is This? (Optional)
- [x] New Content Addition
- [ ] Old Content Deprecation
- [ ] Existing Content Simplification
- [ ] Bug Fix to Existing Content

## Which Manual Does This Relate To? (Optional)
- [x] Admin Manual
- [ ] Developer Manual
- [ ] User Manual
- [ ] Android
- [ ] iOS
- [ ] Branded Clients
- [ ] Desktop Client
- [ ] Other

**Comment by erwinpalma** [comment]
I wrote this notes related with WND

https://gist.github.com/erwinpalma/327297847c71917a6561e5c10a6dadcb

**Comment by enbrnz** [comment]
> https://gist.github.com/erwinpalma/327297847c71917a6561e5c10a6dadcb

I don't think this is helpful, please just flesh out the structure we determined yesterday, which is in my comment at the top. All we need are some screenshots and commands to every single one of the steps.

**Comment by voroyam** [comment]
Can every one assigned write a quick comment what he/she is doing/planing to do?

**Comment by Akidxx** [comment]
I am planning to make an article about owncloud Installation (Manual Installation) with the exact basic steps and add the troubleshooting part where we can put the errors/issues that someone can face during the installation

**Comment by erwinpalma** [comment]
Here is my **draf** about the occ process	

NOTE: I am working on it

enable the option Allow to users... WND

	login into your ownCloud web Site as administrator
		go to admin-->Settings
		and on the left Panel clic on the Admin->Storage
		Enable the option "Allow Network Drive"
(PIC
![allow](https://user-images.githubusercontent.com/30660343/100608688-0e279a80-330d-11eb-9edf-5186eba529f4.png)
)

**Comment by voroyam** [comment]
> I am planning to make an article about owncloud Installation (Manual Installation) with the exact basic steps and add the troubleshooting part where we can put the errors/issues that someone can face during the installation

How far are you in to writing? I would rather discuss a new page with the team instead of going solo on something like this.

**Comment by voroyam** [comment]
> Here is my **draf** about the occ process	
> 
> 
> 
> NOTE: I am working on it
> 
> 
> 
> enable the option Allow to users... WND
> 
> 
> 
> 	login into your ownCloud web Site as administrator
> 
> 		go to admin-->Settings
> 
> 		and on the left Panel clic on the Admin->Storage
> 
> 		Enable the option "Allow Network Drive"
> 
> ![allow](https://user-images.githubusercontent.com/30660343/100608688-0e279a80-330d-11eb-9edf-5186eba529f4.png)
> 
> 
> 
> **Scenario 1**
> 
> You want to share a specific share for all users:
> 
> 
> 
> 
> 
> ```
> 
> occ files_external:create ⁄
> 
> 	-c host=192.168.178.43 ⁄
> 
> 	-c root=share ⁄
> 
> 	-c share=accounts ⁄
> 
> 	-c domain=MyCompany ⁄
> 
> 	'All users' ⁄
> 
> 	windows_network_drive ⁄
> 
> 	password::session-credentials
> 
> ```
> 
> 
> 
> 
> 
> 

Again. Please read the stuff Erik wrote in response to your first comment and tell me what the Task is again. In your own words.

**Comment by Akidxx** [comment]
> > I am planning to make an article about owncloud Installation (Manual Installation) with the exact basic steps and add the troubleshooting part where we can put the errors/issues that someone can face during the installation
> 
> How far are you in to writing? I would rather discuss a new page with the team instead of going solo on something like this.

I described the steps in a draft and need to add screenshots.I want to describe the steps for each OS seperately: Ubuntu, Centos...
Maybe we can discuss it more in the meeting tomorrow..

**Comment by erwinpalma** [comment]
> Again. Please read the stuff Erik wrote in response to your first comment and tell me what the Task is again. In your own words.

I wrote: _NOTE: I am working on it_ and it means that is not finish yet, because I did it, but I am verifying every step again. Wait until the end

And Erick told me that I have a space to write my contribution as a comment.

**Comment by enbrnz** [comment]
Yes, good to see some progress. I see a problem with your first draft: At no point did we mention anything about user added storage, we want a guide for an admin, so your screenshot guide is incorrect. 

I really like the style of how you are highlighting buttons in a screenshot.
I'll put in a follow up for tomorrow afternoon, so we can check on the progress.

**Comment by voroyam** [comment]
> > > I am planning to make an article about owncloud Installation (Manual Installation) with the exact basic steps and add the troubleshooting part where we can put the errors/issues that someone can face during the installation
> > 
> > 
> > How far are you in to writing? I would rather discuss a new page with the team instead of going solo on something like this.
> 
> I described the steps in a draft and need to add screenshots.I want to describe the steps for each OS seperately: Ubuntu, Centos...
> Maybe we can discuss it more in the meeting tomorrow..

Yeah - first discuss then start working. Our docs are ubuntu exclusive.

**Comment by enbrnz** [comment]
```
add-apt-repository ppa:ondrej/php
apt-get update
apt-get install php-smbclient
```

**Comment by erwinpalma** [comment]
This new document should enable an administrator to install and configure a Windows Network Drive share user home drive. This uses user authentication and enables the use of the sync client using the WND listener and process queue.


# 1. Installation
## samba packages & libraries

Verify if the required packages are available with with follow command

```
# php -m | grep smb 
```
You should have a similar output, otherwise install the lib **libsmbclient** and php-smbclient

```
libsmbclient
smbclient
```
- enable ownCloud app windows_network_drive
	occ / WebUI

2. Configuration
2.1 WebUI
- external storage settings of ownCloud, create:
- share: server / path
- credentials: to authenticate use save in database, for using sync client
- user availability
- enable sharing
- "Check for changes"

2.2 Linux
- setup windows network drive listener
two options:
- systemd service
- cron with flock

- setup the process queue

## 2.3 Alternative to WebUI config of share, use `occ`
### Scenario 1: publish a share for all the users

To publish a share for all the users, means that a Share will be accesible for all the users into the ownCloud.

If You want "to publish" a specific share for all users into the owncloud server run the follow command

```
occ files_external:create \
  -c host=192.168.178.43 \
  -c share=CompanyShares \
  -c domain=MyCompany \
  'All users' \
  windows_network_drive \
  password::sessioncredentials
```
### Scenario 2: publish a share for a specific user

In this example we will publish the share \192.168.178.43\test\erwin, were

```
\\192.168.178.43\test\erwin
        |          |    |
        |          |    +----- -c root=
        |          +---------- -c share=
        +--------------------- -c host=
```

Use this command

```
occ files_external:create \
	-c host=192.168.178.43 \
	-c root=erwin \
	-c share=test \
	-c domain=MyCompany \
	'Erwins HOME' \
	windows_network_drive \
	password::sessioncredentials
```
### Scenario 3: publish a share for All users with specific HOME into the Windows Share

Into your windows share you have:

```
\\192.168.178.43\home$\%username%
        |          |    |
        |          |    +----- %username%
        |          +---------- Hidden folder
        +--------------------- Address of the Windows SMB Server
```
Ue this command
```
occ files_external:create \
	-c host=192.168.178.43 \
	-c root=home$ \
	-c share=$user \
	-c domain=MyCompany \
	'HOME SMB' \
	windows_network_drive \
	password::sessioncredentials
```

3. Troubleshooting
- process queue will not work if there is a backslash in the share path configured in webui

**Comment by voroyam** [comment]
What packages do I need to install and how do I install them?￼￼￼￼

**Comment by voroyam** [comment]
How do I enable the wnd app?

**Comment by voroyam** [comment]
![94 130 230 31_8080_server_admin_manual_installation_ubuntu_18_04 html](https://user-images.githubusercontent.com/24212810/101477101-08563880-394f-11eb-9343-95dd20a769a5.png)

**Comment by voroyam** [comment]
done. 

Took me like 2 hours while I was doing other stuff. 

We need obviously to check it and add pictures, but the foundations for this page has been laid. This is what we wanted to get from the plan we have worked out 2 weeks(!) ago.

**Comment by voroyam** [comment]
@enbrnz can you check for accuracy and comment here what's missing or wrong?  I would like to get a rough draft up in docs and then we can always improve on it in separate PRs

**Comment by enbrnz** [comment]
Very Nice! I haven't 100% double checked it yet

Did you put this into the wrong page by mistake? In your screenshot it is highlighting `Install ownCloud on Ubuntu 18.04`

**Comment by voroyam** [comment]
No mistake, this are my local docs. I use them to preview stuff.

**Comment by enbrnz** [comment]
I see you just copied the part about the WND process queue. However there is a copyable cron job for the process queue without flock. As I understand it, you also have to always ensure that there is only one unique process queue process running. Therefore I think we should remove the part where we talk about the process queue running without flock... What do you think?
Otherwise very good, perhaps a few small formatting issues, but I guess we can get them figured out once we have the draft in this repo.

**Comment by voroyam** [comment]
I don't know anything about flock.

I would like to have everything figured out before I make the PR. To then have no discussion in there, just one commit, that we can backport to 10.5 and 10.4. A clean job. We can discuss in here and figure out the kinks.

**Comment by voroyam** [comment]
We can also just leave the part we are not certain about out of the first version and habe just the default process queue.

Then a different someone could add the correct information as a PR. I would always get things of the ground instead of discussing what every detail for a month with then no real changes.

**Comment by enbrnz** [comment]
> I would like to have everything figured out before I make the PR. To then have no discussion in there, just one commit, that we can backport to 10.5 and 10.4. A clean job. We can discuss in here and figure out the kinks.

Agreed

> I don't know anything about flock.

This isn't about flock this is about process-queue. If you want to know more about flock I'd recommend to study its man page.

> We can also just leave the part we are not certain about out of the first version and habe just the default process queue.

I think we should make sure that the process-queue part is unambiguous. I think this already shows that the current documentation is so ambiguous that none of us are certain what it is supposed to say:
process-queue with flock OR without flock? 

I think I've heard @jvillafanez say multiple times that process-queue process needs to never run multiple times at once.



> Then a different someone could add the correct information as a PR. I would always get things of the ground instead of discussing what every detail for a month with then no real changes.

Obviously we should make sure it is as correct as possible, but nobody is perfect.
We can get it out right now, and then work on the rest with small PRs...

**Comment by voroyam** [comment]
![image](https://user-images.githubusercontent.com/24212810/101619711-eecaf480-3a13-11eb-98ed-556be92f8da6.png)

**Comment by voroyam** [comment]
I talked with Carlos - he is also not sure about the process queue command with flock.

He said that we have to run it with flock, and have to specify the path because cron don't always finds the flock command, so we have to write /usr/local/bin/flock instead of just flock in the beginning. Bun why in the example in the docs there is a -n file there - no one knows.

We would need a clear answer from @jvillafanez

**Comment by jvillafanez** [comment]
About the parallel runs of the process-queue, the behaviour heavily depends on the specific notification list. There are several problematic scenarios:
* Duplicated execution for the notification if both process start at the same time. It's expected that the first process deletes the notifications that will be handled, so the second process can't pick them up, but there is no guarantee that this will happen. Although rare, the first process might not be able to delete the notifications on time.
* Different execution order of the notifications if the processes use chunks (which is recommended to keep memory usage under control). Assuming that you have 1000 pending notifications and you set the chunks to 300 for example, it's possible that the first chunk is handled by the first process and the second chunk by the second process.
  The problem is that there could be dependencies among the notifications: "fileA" is modified, then deleted later. If the deletion is processed first, maybe we end up showing the fileA because it has been modified.

Maybe I'm a bit paranoid, but these cases are hard to predict. Even if with the default parameters we might not step into those cases, it's better to stay on the safe side. I think that sometimes it's difficult to understand the output of the process-queue even for me. Parallel runs will make this even harder.

By serializing the execution, we can ensure that those cases won't happen.

Note that we should also serialized the execution when ownCloud runs in multiple servers. Not sure if `flock` works over NFS or similar FS

**Comment by voroyam** [comment]
Okay, what we need is to document the command. @jvillafanez 

What we don't understand right now is what the `-n /my/lock/file` does or how it should work. Is it a random file or a specific one? What permissions does it have to have? What is it for? This is what we need to document.

Please explain **this**.

**Comment by jvillafanez** [comment]
Ok, that's for the `flock` command, it isn't wnd related

The `-n` option will cause the `flock` command to fail instead of waiting if it can't get the lock. Since we expect the process-queue to be run by the cron periodically, we don't really need 3, 5 or 10 processes waiting in a queue until the first process-queue finish. If `flock` can't get the lock, we abort the run. There will be another run to take care of the next bunch of notifications soon enough.

The `/my/lock/file` is a random file or directory that will be used to hold the lock. The file or folder can be anywhere. The only restriction is that all the runs against the same wnd server and share must point to the same file in order to use the same lock.
I expect a cron such as (I'm pretty sure I'm missing things):
```
* * * * * flock -n /tmp/wnd001 occ wnd:process-queue server1 share1
* * * * * flock -n /tmp/wnd002 occ wnd:process-queue server1 share2
* * * * * flock -n /tmp/wnd003 occ wnd:process-queue server2 share3
```
we can run those in parallel because the servers and shares are different, so there won't be collisions. They can be run independently. In fact, they can be run under different schedules without problems (maybe server1+share1 needs more frequent updates than the rest).
In that example, multiple runs of the same command (server1+share1, for example) can overlap. The `flock` command is there to prevent that. The second, (third, fourth, etc) execution won't happen if the first execution is still running.

That's more or less the idea. `flock` also has some additional options that could be useful (waiting some seconds for the lock to be available, for example), but I think that's enough.

**Comment by voroyam** [comment]
Can it be the same file? or does every process require separate file?

**Comment by jvillafanez** [comment]
> Can it be the same file? or does every process require separate file?

It can be the same file, although that would serialize too much. The server1+share2 would need to wait until the server1+share1 has finished.
Note that using the same file for everything could potentially lead to a process starvation: last process might never run if there is always another process running, at least with that setup.

I wouldn't recommend to use the same file for everything.

**Comment by voroyam** [comment]
Okay, then I will take the code block from your example and check if it's correct and use it in our docs.

Thank you
