### ISSUE TITLE
Improve Visibility for Upload via Curl to public Links

### ISSUE THREAD

**Issue by voroyam** [owncloud/docs#2907]
## WHAT Needs to be Documented?
We need to improve visibility for the section below

## WHERE Does This Need To Be Documented (Link)?
https://doc.owncloud.com/server/user_manual/files/access_webdav.html#uploading-files-to-a-public-link-using-curl

## WHY Should This Change Be Made?
A user in central did not find it, and had to spend his time searching 

https://central.owncloud.org/t/upload-to-file-drop-via-curl/29287

I had to search Chat history, then look for the PR on GH and then I saw that it was in the user manual. But then I had to search where it's exactly.

I typed in the search field Public Link, File Drop, Upload. But nothing useful came.

## (Optional) What Type Of Content Change Is This? 
- [ ] New Content Addition
- [ ] Old Content Deprecation
- [x] Existing Content Simplification
- [ ] Bug Fix to Existing Content

## (Optional) Which Manual Does This Relate To?
- [ ] Admin Manual
- [ ] Developer Manual
- [x] User Manual
- [ ] Android
- [ ] iOS
- [ ] Branded Clients
- [ ] Desktop Client
- [ ] Other

**Comment by ediathome** [comment]
@voroyam Hey Dmitry! Thanks for creating this issue which describes my problem very well. I think the issue was that public upload links are often referred to as "File drops" whereas in the documentation this is only called a "Uploading Files to a **Public Link** Using cURL". Maybe we could add the term "File drop" in the documentation? Cheers Martin

**Comment by mschreml** [comment]
@ediathome we added the keyword. Thank You!
