### ISSUE TITLE
Inconsistent page availability

### ISSUE THREAD

**Issue by cortho** [owncloud/docs#3191]
Use case: Search owncloud docs how to set up an LDAP proxy.

## Steps to reproduce 
1. Enter https://doc.owncloud.com and type **ldap proxy** or even **ldap proxy cache** to the search box.
-> no useful result found

2. Search google for _owncloud ldap proxy cache_ - first result here is https://doc.owncloud.com/server/10.2/admin_manual/configuration/ldap/ldap_proxy_cache_server_setup.html - note version 10.2

3. Search duckduckgo for _owncloud ldap proxy cache_ - first result here is https://doc.owncloud.com/server/admin_manual/configuration/user/user_auth_ldap.html

## Resulting questions
* How is it possible that exising information gets lost in later releases' documentation? (available in 10.2 but not available in 10.6)
* To which server version does the link in step 3 point, doc.owncloud,com/server without explicit version? (obviously not to _latest_)
* How is it possible, when entering __ldap proxy cache__ into the search box of even https://doc.owncloud.com/server/10.2/ the result is not listed in the top results?
* In general the search result quality is very low. When I enter _ldap_ into the search box of https://doc.owncloud.com/server/10.6/ the first three highest score result are more or less the same results only for different versions (latest, 10.5, 10.6). From my experience I rather find results by using google than with the internal search functionality.

Edit: In https://doc.owncloud.com/server/10.2/admin_manual/configuration/ldap/ldap_proxy_cache_server_setup.html#configure-the-server the example slapd.conf was obviously pasted twice.

**Comment by voroyam** [comment]
Hey Cortho,

the issue here is that We [ I ]  wanted to remove that part of the docs because it was setup one as a proof of concept once during oC 9 and is now not needed because of oC 10 mechanism on how the LDAP users get pulled.

Now - in the current docs releases removing a page is no big issue, but in prior releases there are problems removing stuff. The doc builds fail and you can't do anything.

That's why you still find that part in the older docs and not in the newer docs.
