### ISSUE TITLE
discrepancy between 10.6/master and 10.5 on The files:transfer-ownership command

### ISSUE THREAD

**Issue by voroyam** [owncloud/docs#3257]
## WHAT Needs to be Documented?
we need to decide what to keep and what to remove

## WHERE Does This Need To Be Documented (Link)?
https://doc.owncloud.com/server/10.5/admin_manual/configuration/server/occ_command.html#the-filestransfer-ownership-command

## WHY Should This Change Be Made?
because master and 10.6 have different content on that topic than 10.5

## 10.5

![image](https://user-images.githubusercontent.com/24212810/109832677-e106c300-7c40-11eb-89ca-fcb737fd36d2.png)

## master and 10.6

![image](https://user-images.githubusercontent.com/24212810/109832799-ff6cbe80-7c40-11eb-9f03-3405678b2ed8.png)

## Summery

10.5 is missing the arguments and options part. need to be included.

**Comment by phil-davis** [comment]
@voroyam I edited the title (see "changed the title" GitHub entry above) I think that is what you meant?

**Comment by voroyam** [comment]
Yeah, sorry. I had to fight with git because of a merge conflict and then I noticed the discrepancy that was causing all the merge conflicts on this specific point.

**Comment by phil-davis** [comment]
I guess that there are other older changes that did not get backported to 10.5.

https://github.com/owncloud/docs/pull/2912

https://github.com/owncloud/docs/pull/2912#issuecomment-740678468

That was not backported to 10.5. But I had commented "This command is to be released in 10.6.0 - so no backport needed. (Unless we want to try and manually "backport" the other changes made here that are not directly about the new command)"

So the problem seems to be that there were mixed changes done in #2912 -
1) reorganizing the existing information
2) making changes that apply to 10.6

So someone should sort out what diffs are (1) and apply those to 10.5. Then the next backport(s) that touch this stuff should apply more easily.

**Comment by voroyam** [comment]
Let me try to understand this: the new feature / command was `files:troubleshoot-transfer-ownership` , correct?

But, because someone made a bunch of changes to some other things in the same PR, we now have an inconsistent state. Correct?

If my two assumptions are correct, then the same someone who decided to make the changes should now be responsible of fixing this inconsistent state.

**Comment by phil-davis** [comment]
The PR seems to have had both re-formatting/re-organising changes and also real changes for things that changed in 10.6.
The re-formatting/re-organising changes need to be manually sorted out as a "backport" PR to 10.5. That will make it easier to backport other future edits from master/10.6 to 10.5 (if they are relevant to 10.5)

Either:
- the documentation in 10.5 stays as it is, and we simply do not backport  stuff relates to transfer-ownership, or;
- "someone" sorts out the re-formatting/re-organising changes that need to be applied back in 10.5
- or I am completely wrong (it all depends on exactly how the the transfer-ownership command worked in 10.5)

**Comment by voroyam** [comment]
not a real answer to any of my questions.

With 10.7 10.5 becomes obsolete. Too much work I would say.
