### ISSUE TITLE
update to config.sample.php comment suggestion

### ISSUE THREAD

**Issue by voroyam** [owncloud/docs#331]
We should include "mid large installations" in the comment about transactional file locking: 

```
Enables transactional file locking.
 * This is enabled by default.
 *
 * Prevents concurrent processes from accessing the same files
 * at the same time. Can help prevent side effects that would
 * be caused by concurrent operations. Mainly relevant for
 * very large installations with many users working with
 * shared files.
```

Could be changed to:

```
...
Mainly relevant for
 * very large or mid large installations with many users working with
 * shared files.
```

https://github.com/owncloud/core/blob/master/config/config.sample.php#L1318

also, we should include this 2 lines of configuration:

```
'filelocking.enabled' => 'true',
'memcache.locking' => '\\OC\\Memcache\\Redis',
```

**Comment by settermjd** [comment]
@PVince81 @pako81 can you provide further feedback on this, please?

**Comment by pako81** [comment]
I would rather suggest removing the part "Mainly relevant for very large installations with many users working with shared files." since we are already advising Redis for Transactional File Locking even in case of single-server setups:

https://doc.owncloud.com/server/10.0/admin_manual/configuration/server/caching_configuration.html?highlight=caching#small-organization-single-server-setup
