### ISSUE TITLE
[QA] go link to admin-cli-upgrade is a 404

### ISSUE THREAD

**Issue by jnweiger** [owncloud/docs#3379]
Seen in server 10.7.0 RC1

* upgrade an app that triggers an upgrade process. E.g. files_pdfviewer 0.12.0 over files_pdfviewer 0.11.2
* visit the website, there is no login offered, but information ow to do the upgrade. OK
* there is a link to documentation
![image](https://user-images.githubusercontent.com/1108546/111709609-34cff980-8848-11eb-8d5b-cba19fd1a51b.png)

* this link https://doc.owncloud.org/server/10.7/go.php?to=admin-cli-upgrade results in 404

Expected behaviour: the link resolves to https://doc.owncloud.org/server/10.7/admin_manual/configuration/server/occ_command.html#command-line-upgrade

**Comment by mmattel** [comment]
- With regards to `Expected behaviour: the link resolves to`
*Never* use the lates version branch name directly like `10.7` use instead `latest` which resolves to the correct version number. `latest` has been introduced to avoid ongoing maintenance when a version changes.
- With regards to `/go.php?`
docs itself has no `go.php` program to resolve any parameters to links. I expect this to be part of the web backend (Just double checked running a grep over the docs repo). Docs itself references in the developer manual to go.php exactly once (`modules/developer_manual/pages/core/theming.adoc:472`) 

Adding @xoxys 
@EParzefall  FYI

**Comment by xoxys** [comment]
That's not an issue for the docs team right now.... Clarifying...

**Comment by jnweiger** [comment]
This link is generated by server code. I don't think, that the deploying admin should have to set the version number himself. Please consult with engineering, if this should be changed.

I understand, this still needs to be configured in https://gitea.owncloud.services/devops/websites ansible/roles/docs/templates/config.j2
Does anyone from the doc team have access there?

**Comment by mmattel** [comment]
> Does anyone from the doc team have access there?

I can speak only for myself, but I am not aware of

**Comment by jnweiger** [comment]
Found my old 10.6 PR. Will craft a 10.7. PR from that.

**Comment by jnweiger** [comment]
PR for one ansible config.jq done. Not sure if
* anything else needs to be done
* if it can be deployed like that before the official release
* how it is to be deployed.

**Comment by xoxys** [comment]
> * anything else needs to be done

Afaik not.

> * if it can be deployed like that before the official release

Yes but it will rselect https://doc.owncloud.com/server/10.7/ as default.

> * how it is to be deployed.

Gets automatically deployed on PR merge.

**Comment by jnweiger** [comment]
Fixed via https://gitea.owncloud.services/devops/websites/pulls/140
