### ISSUE TITLE
php-smbclient from ondrey is incompatible with owncloud-10.7.0

### ISSUE THREAD

**Issue by jnweiger** [owncloud/docs#3450]
I'd suggest that the 20.04 quick install guide https://doc.owncloud.com/server/admin_manual/installation/quick_guides/ubuntu_20_04.html#install-the-recommended-packages should discuss the php7.4 and php-8.0 isuse. As is, the guide would not work with ubuntu 20.10 and up.

(Seen while proposing https://github.com/owncloud/docs/pull/3449)

Ondrey and other php vendors have switched their default to php-8.0
that is, when you ask for `apt install php-XYZ` you now get a package for 8.0 and not for 7.4

With owncloud 10.7 we require php 7.4 -- 8.0 won't work.

The ondrey repo is requied to provide php...-smbclient, which is a dependency for windows_network_drive.
With the name `php-smbclient` it is very likely, that we install the php-8.0 version. 
We should explicitly name it  `php7.4-smbclient` -- probably the same applies for all other php-XXX packages.

**Comment by jnweiger** [comment]
@TheRealBro we recomend Ondrey's ppa in the quick install guide. Should we recommend `pecl install smbclient-stable` instead?

**Comment by mmattel** [comment]
First having the ondrej ppa in 20.04 is pointless as 20.04 ships with php7.4 and the ondrej ppa is necessary if you want to use php7.4 with U18.04. The only reason for using the ondrej ppa in 20.04 is, when you want to use php8 - which we atm do not support. Please see the full install guides for 20.04 to get a working configuration including the requirements for WND. There is more you have to take care when doing a preperation for 20.04.

**Comment by EParzefall** [comment]
@mmattel The problem with Ubuntu 20.4 is that they have dropped the php-smbclient package, therefore we also need a different source with php 7.3 and 7.4. as well.

**Comment by jnweiger** [comment]
The above is a bit convoluted. Sorry for this. To be very clear what my suggestion is:
The correct way to install php-smbclient using Ondrey's repo is this:

```
add-apt-repository ppa:ondrej/php
apt update
apt install php7.4-smbclient
```

The docs currently do not specify 7.4, but ownCloud requires exactly 7.4 (not 7.2, not 8.0)
As soon as we fix this, the instructions work again.

**Comment by mmattel** [comment]
To make things more clear and understandable:

`php-smbclient` ... smbclient is a PHP extension that uses Samba's libsmbclient library to provide Samba related functions and 'smb' streams to PHP programs...

See:
https://packages.ubuntu.com/de/bionic/php-smbclient
and
https://packages.debian.org/de/stretch/php-smbclient
and
https://github.com/eduardok/libsmbclient-php#libsmbclient-php-a-php-wrapper-for-libsmbclient

Both `php-smbclient` and `libsmbclient-php` are identical but have historically different namings.

From U20.04 onwards `php-smbclient` has been removed from the package list and needs to be installed by the originators package `libsmbclient-php` - which is always much newer and regulary updated. It can be installed in different ways, either from github or better via PECL.

**IMPORTANT**
It is important to know, that a particular `libsmbclient-php` version (and also was `php-smbclient`) is bound to a particular php version. This means, that the same `.so` file cant be used for other PHP versions than to the bound (compiled) one. You will get an error when trying.

With U18.04 the prerequisite for running ownCloud in a newer version did not met the minimum PHP requirement. The ondrej package was a good workaround to get at least the minimum required version, respectively the latest supported version PHP 7.4

Starting with U20.04, PHP is shipped by default with version PHP7.4 which meets all ownCloud requirements. PHP8 is not supported by oC at all and therefore not needed.

To use SMB/WND, the only thing you have to do is to install `libsmbclient-php` which is well described in the manual installation guide and a easy task.

Having an enterprise customer, the statement is also true for the community, there is no need to install the ondrej package for U20.04 just because of `php-smbclient`. The ondrej package always gets all versions of PHP, usually selects the latest PHP release by default (PHP8, not supported) and you have to select which one you want to use in a manual process, which can be error prone. And, you **MUST NOT** run the native provided U20.04 PHP version in parallel with the ondrej package, not in any aspect.

**Summary**
- There is no need and no benefit for the ondrej PHP package in U20.04 or later
- You cant have both, the native and the ondrej package installed in parallel
- We have a full working description for installing and updating `libsmbclient-php`
- We have a full working description how to process an upgrade from U18.04 to U20.04 including the switch from ondrej to native or a fresh install of U20.04
- We avoid a lot of confusion, misconfiguration and frustration by using the on board provided PHP7.4 version for U20.04
- Enterprise customers do not want to tinker around on productive environments but use proven and easy processes which will not break on a system update

**Comment by michl19** [comment]
@micbar @pmaier1 Please have a look into this issue give guidance what to do.

**Comment by cdamken** [comment]
> add-apt-repository ppa:ondrej/php
> apt update
> apt install php7.4-smbclient

I see there is a missing step

after the update you have to run an upgrade to change the default PHP to the one from ondrej, otherwise, you have mixed PHP versions and does not work correctly

Additionally you have to force the 7.4 as explained in:
https://tecadmin.net/switch-between-multiple-php-version-on-ubuntu/

**Comment by mmattel** [comment]
See my description above, it explains this extensively and describes how to get out of the mess.

**Comment by cdamken** [comment]
I read it and PECL is not the solution either, at least Ondrej is always with the latest fixes,
It's the same thing if we also recommend [eduardok](https://github.com/eduardok/libsmbclient-php) instead.

We have a valid method that has been working fine in many servers, is tested and validated in versions 16.04.18.04, 20.04. and let you also have control over which PHP version are you running.
That's why recommend what we have been testing and working on successfully until now, if we want to switch to PECL, then we have to do all the testings again.

**Comment by pmaier1** [comment]
> We have a valid method that has been working fine in many servers, is tested and validated in versions 16.04.18.04, 20.04. and let you also have control over which PHP version are you running.

Thanks, that sounds great. Where is it documented?

**Comment by EParzefall** [comment]
@cdamken  @pmaier1 We actually have a section in the admin guide: https://doc.owncloud.com/server/10.7/admin_manual/installation/manual_installation/server_prep_ubuntu_20.04.html#multiple-concurrent-php-versions
However, that's not really something for a quick install guide, I think. Besides, I'm getting errors when switching to the correct compiling environment as described in the manual:
# sudo update-alternatives --set phpize /usr/bin/phpize7.4
update-alternatives: error: no alternatives for phpize
# sudo update-alternatives --set php-config /usr/bin/php-config7.4
update-alternatives: error: no alternatives for php-config
I'd vote for a pecl install from eduardok at least for the quick install guide: https://github.com/eduardok/libsmbclient-php

**Comment by pmaier1** [comment]
@cdamken Please check and let us know the official recommendation from ownCloud support.

**Comment by jnweiger** [comment]
To roughly summarize:

* We have naming confusion. The following mean all the same thing, but live in distinct domains:
   - php-smbclient is a DEB package name. 
   - libsmbclient-php is name of the source tar, as released by Eduardo
   - smbclient or smbclient-stable are PECL names 

* We have multiple different ways to fulfill our WND dependencies:
  - DEB package from Ubuntu (worked fine until before 20.04, since 20.04 a php-smbclient ist not included)
  - DEB package from Ondrey (available for recent Ubuntu versions, even 21.04 -- unfortunately Martin reports, that it does not work together with Ubuntu php)
  - PECL packages (work everywhere, when compiled correctly)

The unsolved dilemma I see here, is:
* For my personal use, I'd also always go with PECL these days.
* For an enterprise use case, I'd never go with PECL, I'd always ask for proper DEB packages. (infrastructure separation and reproducability reasons).
* Considering the pecularities of the alternatives, I no longer have a solution for my enterprise use case.

**Comment by mmattel** [comment]
@jnweiger Great summarisation !

Three points to add:
- ownCloud itself is using the pecl smbclient-stable wrapper install for its own docker environment and it is therefore in enterprise use and will be massively used with the release of QNAP.
- A DEB package is based on either the source or pecl (where pecl is based on the source anyways but eases the installation process).
- We already have a proper and easy documentation for installing the wrapper.

**Comment by michl19** [comment]
@cdamken @mmattel @jnweiger @EParzefall @pmaier1 
Good discussion. Do we have alignment for a solution? If so, how does the solution look?

**Comment by michl19** [comment]
@cdamken, @jnweiger @pmaier1 @micbar 
ping - how should the doc team go ahead? 
- pecl would need another 15h doc effort (pecl is used for docker and seems to doc team less complicated from an user view)
- using ondrey (multiple versions of php) would need another 40h doc effort

**Comment by micbar** [comment]
We should remove the WND parts from the quick guide.

**Comment by mmattel** [comment]
Closing via #3858
