### ISSUE TITLE
Update occ encryption:fix-encrypted-version when no fix was found

### ISSUE THREAD

**Issue by mmattel** [owncloud/docs#3594]
## WHAT Needs to be Documented?
Just a text addon to tell what we are doing in case this occurs

References: https://github.com/owncloud/encryption/pull/273 (Restore encrypted version to original if no fix was found)
Merged, only for master (and 10.8)

## WHERE Does This Need To Be Documented (Link)?
https://doc.owncloud.com/server/admin_manual/configuration/server/occ_command.html#fix-encrypted-version

## WHY Should This Change Be Made?
Completness of docs

## (Optional) What Type Of Content Change Is This? 
- [ ] New Content Addition
- [ ] Old Content Deprecation
- [ ] Existing Content Simplification
- [x] Bug Fix to Existing Content

## (Optional) Which Manual Does This Relate To?
- [x] Admin Manual
- [ ] Developer Manual
- [ ] User Manual
- [ ] Android
- [ ] iOS
- [ ] Branded Clients
- [ ] Desktop Client
- [ ] Other

@IljaN @karakayasemi

**Comment by IljaN** [comment]
### Context
The oc_filecache contains the integer columns "version" and "encryptedVersion"  which start with 1 (integer) and are incremented on every file modification. 

When using encryption those values are used together with the ciphertext to generate a cryptographic signature for the file. Conversely the version value is required to verify the signature.

In some rare cases (timeouts, bugs,...) the value might not get updated accordingly or lost, thus requiring to bruteforce the version with the fix:encrypted:version command until the file can be encrypted.

owncloud/encryption#273 changes the behavior of the command so that the encryptedVersion value is reset to it's original value if no correct version was found. Before the fix the last tried value was stored in the database, thus modifying the state of the system and making further rescue attempts non-deterministic.

**Comment by mmattel** [comment]
> bruteforce the version with the fix:encrypted:version command until the file can be encrypted.

did you mean encrypted or decrypted?

Note: the text is very helpful to describe what this command intends to do. In case, I will ask questions.

**Comment by IljaN** [comment]
*decrypted

**Comment by mmattel** [comment]
@IljaN 
what indicates an admin to run this command, or in other words, what problem does the admin run into that he can identify to use this command to fix it?

**Comment by IljaN** [comment]
He will get an "Invalid Signature" message in the UI or the Dekstop Client
