### ISSUE TITLE
occ commands for HSM not documented 

### ISSUE THREAD

**Issue by mmattel** [owncloud/docs#3724]
## WHAT Needs to be Documented?
[HSMDaemon.php](https://github.com/owncloud/encryption/blob/62cf704127c9f5f3a79e00e294c6771b10f9ab27/lib/Command/HSMDaemon.php) and [HSMDaemonDecrypt.php](https://github.com/owncloud/encryption/blob/62cf704127c9f5f3a79e00e294c6771b10f9ab27/lib/Command/HSMDaemonDecrypt.php)

occ commands to be documented:
```
encryption:hsmdaemon export-masterkey|import-masterkey
encryption:hsmdaemon:decrypt
```
and
`config:app:set encryption hsm.url --value 'http://localhost:8513'`
`config:app:set encryption hsm.jwt.secret --value '7a7d1826-b514-4d9f-afc7-a7485084e8de'`
`config:app:set encryption hsm.jwt.clockskew --value 120` in seconds
`config:app:set encryption masterKeyId --value ??`
`config:app:set encryption recoveryKeyId --value ??`
`config:app:set encryption useMasterKey --value ??`
`config:app:set encryption encryptHomeStorage --value ??`
`config:app:set encryption crypto.engine --value 'internal | hsm'`
`config:app:set encryption recoveryAdminEnabled --value ??`
`config:app:set encryption userSpecificKey --value ??`

## WHERE Does This Need To Be Documented (Link)?
https://doc.owncloud.com/server/admin_manual/configuration/server/occ_command.html#encryption
Backporting to be defined

## WHY Should This Change Be Made?
Missing commands, must be documented

## (Optional) What Type Of Content Change Is This? 
- [x] New Content Addition
- [ ] Old Content Deprecation
- [ ] Existing Content Simplification
- [ ] Bug Fix to Existing Content

## (Optional) Which Manual Does This Relate To?
- [x] Admin Manual
- [ ] Developer Manual
- [ ] User Manual
- [ ] Android
- [ ] iOS
- [ ] Branded Clients
- [ ] Desktop Client
- [ ] Other

@jnweiger @IljaN @JammingBen @pmaier1 fyi

**Comment by IljaN** [comment]
`config:app:set encryption hsm.url --value 'http://localhost:8513`
Sets the urls on which the hsmdaemon's rest-api is reachable

`config:app:set encryption hsm.jwt.secret --value '7a7d1826-b514-4d9f-afc7-a7485084e8de`
Consumers of hsmdaemons api (ownCloud in this case) must authenticate with a JWT. This Secret is shared between hsdmdaemon and ownCloud to sign the JWT. 

The JWT mentioned above has an expiry timestamp. In case the time-clocks on the ownCloud and hsmdaemon system drift/skew appart we add some additional time to the expiry to counteract this.
`config:app:set encryption hsm.jwt.clockskew --value 120 in seconds`


The values bellow mostly represent internal configuration state and should not be set by the user directly. They are controlled by respective encryption-commands. Change only if you know what you are doing or are debugging.

`config:app:set encryption masterKeyId --value ??`
`config:app:set encryption recoveryKeyId --value ??`
The ID of the respective key. Background: Instead of giving a path to a keyfile (which might be error-prone) an explicit key-id which is part of the key is given. This is also done to accomodate for Keystorages which might not be file-based.

`config:app:set encryption useMasterKey --value 1/0`
Is masterkey encryption enabled?

`config:app:set encryption encryptHomeStorage --value 1/0`

The primary purpose of the ownCloud server-side encryption is to protect users’ files when they’re located on remote storages, such as Dropbox and Google Drive, and to do it smoothly and seamlessly from within ownCloud.

From ownCloud 9.0, server-side encryption for local and remote storages can operate independently of each other. By doing so, you can encrypt a remote storage without also having to encrypt your home storage on your ownCloud server.

`config:app:set encryption crypto.engine --value 'internal | hsm`
Normal ownCloud encryption vs storing decryption-keys in a HSM


`config:app:set encryption recoveryAdminEnabled --value 1/0`
With user-key encryption where only the specific user (not even the admin) can decrypt his data with his password there is an additional option to provide a recovery-key to the admin so he can also decrypt the data if the user leaves the company for example.

`config:app:set encryption userSpecificKey --value 1/0`
I set to 1 if userKey encryption is enabled

**Comment by IljaN** [comment]
`encryption:hsmdaemon:decrypt`

Allows to test the hsmdaemon setup by providing an encrypted string to ownCloud and test if it can be decrypted.

**Comment by mmattel** [comment]
Thanks for the info on `hsmdeamon:decrypt` ✔️ will add the text.
Can you also bring more light into `encryption:hsmdaemon export-masterkey|import-masterkey` ?
I understand what import/export means, but not the impact/when to use for hsmdeamon.
