### ISSUE TITLE
Add skip step to Drone config

### ISSUE THREAD

**Issue by pascalwengerter** [owncloud/docs#4253]
## WHAT needs to be done?
Add a **skip** step to the `.drone.star` that stops currently running builds when a new one is started

## WHY Should This Change Be Made?
Because accepting commit suggestions in the GitHub UI automatically _commits and pushes_, leading to ~70 queued (and fully executed) pipelines yesterday within a couple of minutes for (from the small sample I took) each single line typo fix approved by the docs team.

@wkloucek can I interest you? 😬

**Comment by phil-davis** [comment]
Note: separate education for GitHub users ( @mmattel @EParzefall and ?)

When there are multiple review suggestions, you can go to the "Files Changes" tab of the PR. GitHub allows you to add each suggestion to a "batch" and then create a single commit for all the PR review suggestions. That avoids creating "a dozen" different commits from the review(s).

(This issue is still a good thing to do, also!)

**Comment by mmattel** [comment]
I was not aware about this. Will try/test next time. Thanks for highlighting.

**Comment by mmattel** [comment]
I have tested to batch commit suggestions and this works very well.
Will be taken as default in the future when there are multiple suggestions to commit 😃 

Closing

**Comment by phil-davis** [comment]
This issue is actually about adding the logic to drone that automatically cancels an existing running build when a new commit and build starts. We do that in most other repos and it works nicely - reopening.
