### ISSUE TITLE
Installations in web root vs. subdirectory owncloud fails with error 0B of space available

### ISSUE THREAD

**Issue by daniel712** [owncloud/docs#4825]
debian 11 on 5.10.0-21
nginx 1.22 with php 7.4
oc 10.12.0

When i install the software in the webroot directory NOT in subdirectory owncloud, the installation runs through, but after login the firstrunwizard shows of blank page "This content failed to load" and there is no upload possible with error "Access denied to folder "/". Not enough free space [..] 0B space available.
Also the Quota setting always reverts to "default"

However i am able to create folders and text files in the browser. But no upload possible.

When i install the instance in any webroot folder (e.g. /owncloud) everything works. But i would love to install in webroot to get rid of (https://example.domain.com/OWNCLOUD/login...) owncloud-term in the URLs...

Thanks for fixing this
  Daniel

PS: i read about this in an earlier issue where it was marked fixed, but still remains...
PPS: i think more than 95% of admins install in sub owncloud as in the manual or similar, thats why the bug is not to widely spread...

**Comment by phil-davis** [comment]
Note: issue https://github.com/owncloud/core/issues/40696 describes the opposite problem. There is a known issue with 10.12.0 when installed into a subdirectory. That has been fixed by PR https://github.com/owncloud/core/pull/40697 and a release 10.12.1 will happen soon.

Or do you have a 32-bit system? There was an issue with 32-bit systems that is fixed by https://github.com/owncloud/core/pull/40709 and will also be in the 10.12.1 release.

**Comment by daniel712** [comment]
Thanks for the info! My install is on 64bit. Unfortunaltely the problem here happens the other way round, when i am installing in webroot...
Like described, i am running nginx, so i cannot say something about apache rewrite rules. Can anybody reproduce the problem on a LEMP stack? I used exactly the nginx config for the webroot out of the manual.

Thanks!

**Comment by mmattel** [comment]
@daniel712 I am running owncloud in the webroot since ages successfully on nginx without any issues. Without any claim for completeness or eligability for support, you can take a look into my personal repository where I have a nginx description part you can derive from. For me this seems to be an webserver (nginx) setup and not and owncloud issue.

**Comment by ho4ho** [comment]
Also why posting by docs tracker, look more like support needing by https://central.owncloud.org/

**Comment by mmattel** [comment]
Pls continue on central as suggested, closing.
