### ISSUE TITLE
[QA] permalink go.php?to=admin-encryption is broken

### ISSUE THREAD

**Issue by jnweiger** [owncloud/docs#4883]
Seen with https://github.com/owncloud/QA/blob/master/tools/core-test-doc-links.sh 
One of our  go.php links seems broken today:
```
checking https://doc.owncloud.com/server/latest/go.php?to=admin-encryption -> 404
	ERROR: return code should be 200
	ERROR: Please compare lib/public/Constants.php and web server config
checking https://doc.owncloud.org/server/latest/go.php?to=admin-encryption -> 200
```
.com is failing, .org works, ... BAD.

**Comment by mmattel** [comment]
Not fully correct...
* .org only responses with a 200 because .org redirects to .com without any sub paths
* `https://doc.owncloud.com/server/latest/go.php?to=admin-encryption` -->
`https://doc.owncloud.com/server/10.13/admin_manual/configuration/files/encryption_configuration.html` `https://doc.owncloud.com/server/10.13/admin_manual/configuration/files/encryption/encryption_configuration.html`

There is one path part missing: `encryption`.

I will inform sysadmin to fix it and keep you in cc.
