### ISSUE TITLE
Change the idattribute

### ISSUE THREAD

**Issue by mmattel** [owncloud/docs#4885]
Based on a discussion in chat with @voroyam 

Change the `idattribute` from `-` --> `_`

The change itself is easy and a no-brainer, but the impact needs evaluation especially for permalinks coming from external and if there are any changes in the go template on the webserver necessary.

This should be done when we have the docs dev framework present, see #4874

**Comment by xoxys** [comment]
This doesn't make any sense. Hyphen are valid URL characters and used in many other websites as well. Just because one tool has issues with auto-formatting such links (in case of Kopano Web there is an easy fix, edit the link with the "Insert/edit link" button) we don't need to break all existing links with hyphens for no reason. Please don't.

**Comment by mmattel** [comment]
I have made more thoughts overnight (no I did not dream about...).

@xoxys you are right, Kopano or Outlook have this capability and I also referred in the chat to that. I have been told that there are other systems we use sending emails which seem lacking that capability...

Finally, the main reason that speaks against is the effort to fix internal references to anchors docs itself is using. These would need to get fixed and there are a lot of.

As the positive impact of that change is not in balance with the effort needed, I am closing that issue.
