### ISSUE TITLE
occ files:scan : adding a link to known limitations

### ISSUE THREAD

**Issue by mmattel** [owncloud/docs#507]
## What Type Of Content Change Is This?

- [ ] New Content Addition
- [ ] Old Content Deprecation
- [ ] Existing Content Simplification
- [x] Bug Fix to Existing Content

## Which Manual Does This Relate To?

- [x] Admin Manual
- [ ] Developer Manual
- [ ] User Manual

## What Needs to be Documented?

Referencing the discussion in: https://github.com/owncloud/core/issues/34010

## Why Should This Change Be Made?

Doc improvement

**Comment by settermjd** [comment]
@mmattel, I had a read through https://github.com/owncloud/core/issues/34010 and need further clarification on what is required. Is this issue asking for the documentation of a limitation on scanning external/personal mounts, because the relevant credentials are not stored in session by ownCloud? If not, can you please clarify my lack of understanding here?
