### ISSUE TITLE
Unresolved directive in <stdin>

### ISSUE THREAD

**Issue by mmattel** [owncloud/docs#81]
Just seen while browsing th new doc:

https://github.com/owncloud/docs/blob/master/modules/ROOT/pages/installation/nginx_configuration.adoc

Unresolved directive in <stdin> - include::{examplesdir}/installation/nginx/default-configuration.conf[]
and
Unresolved directive in <stdin> - include::{examplesdir}/installation/nginx/subdirectory-configuration.conf[]

Or is this a normal thing ?

**Comment by settermjd** [comment]
This happens when previewing documentation that isn't generated by Antora. In the screenshot below, you can see that, when generated with Antora, the code example renders correctly.
![bildschirmfoto 2018-10-01 um 12 59 39](https://user-images.githubusercontent.com/196801/46284963-011a8f80-c57a-11e8-834d-02e2c819ab85.png)

**Comment by mmattel** [comment]
Thanks
